---
# Source: cowweb-helm/templates/cowweb.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: cowweb
spec:
  type: NodePort
  selector:
    app: cowweb
  ports:
  - name: http
    port: 80
    targetPort: 8080
    
    nodePort: 30080
    
    
  - name: debug
    port: 8081
    targetPort: 8081
    
    nodePort: 30081
    
    
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: staging
  name: cowweb
  labels:
    app: cowweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cowweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cowweb
    spec:
      containers:
      - name: cowweb
        image: hhayakaw/cowweb:v1.0-release-f09df3fb90028ae4a4a5d2a7bada6f6468cc0f5b
        ports:
        - name: api
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /cowsay/ping
            port: api
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /cowsay/ping
            port: api
          initialDelaySeconds: 15
          periodSeconds: 20
